version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "daily"
    groups:
      front:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "daily"
    groups:
      back:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/frontend/src"
    schedule:
      interval: "daily"
    groups:
      front:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/backend"
    schedule:
      interval: "daily"
    groups:
      back:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directories:
      - "/.github/"
    schedule:
      interval: "daily"
    groups:
      actions:
        patterns:
          - "*"
