version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/frontend"
      - "/backend"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/frontend/src"
    schedule:
      interval: "daily"

  - package-ecosystem: "uv"
    directory: "/backend"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directories:
      - "/.github/"
    schedule:
      interval: "daily"
    groups:
      codeql:
        patterns:
          - "github/codeql-action"
      misc:
        patterns:
          - "*"
        exclude-patterns:
          - "github/codeql-action"
