# This is used by the action https://github.com/dorny/paths-filter

frontend:
  - 'frontend/**'

frontend_dockerfile:
  - 'frontend/Dockerfile'

backend:
  - 'backend/**'

backend_dockerfile:
  - 'backend/Dockerfile'

actions:
  - '.github/workflows/**'
  - '.github/dependabot.yml'
