log:
  quiet: true
  level: 'warn'

output:
  - "cyclonedx-json@1.6=/tmp/sbom.json"

check-for-app-update: true

default-catalogers: []
select-catalogers: []

license:
  content: 'unknown'
  coverage: 75

scope: 'all-layers'
