log:
  quiet: false
  level: "info"
output:
  - table
pretty: true
only-fixed: true
only-notfixed: false
ignore: []
  - vulnerability: CVE-2026-15308
    fix-state: fixed
    reason: "To fix this, we need to upgrade the base image to 3.15, which is not possible at this time."
fail-on-severity: high
show-suppressed: true
sort-by: "risk"
alerts:
  enable-eol-distro-warnings: true
