service: default
runtime: python39
entrypoint: gunicorn --bind 0.0.0.0:$PORT -w 4 -k uvicorn.workers.UvicornWorker main:app

instance_class: F1
service_account: blog-backend-account@personal-blog-backend-64862.iam.gserviceaccount.com

includes:
  - .env

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

automatic_scaling:
  target_cpu_utilization: 0.8
  min_instances: 1
  max_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: 15s
  max_concurrent_requests: 50
