"""add index

Revision ID: 1ba95a45cc2f
Revises: 2819217ecfb7
Create Date: 2025-11-11 19:16:18.404107

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "1ba95a45cc2f"
down_revision: str | Sequence[str] | None = "2819217ecfb7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_index(op.f("ix_comment_id"), "comment", ["id"], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_comment_id"), table_name="comment")
  # ### end Alembic commands ###
