"""init comments table

Revision ID: 2819217ecfb7
Revises:
Create Date: 2025-11-11 15:15:01.540040

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "2819217ecfb7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "comment",
    sa.Column("site_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("post_slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("parent_id", sa.Integer(), nullable=True),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("approved", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(
      ["parent_id"],
      ["comment.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    op.f("ix_comment_post_slug"), "comment", ["post_slug"], unique=False
  )
  op.create_index(
    op.f("ix_comment_site_id"), "comment", ["site_id"], unique=False
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_comment_site_id"), table_name="comment")
  op.drop_index(op.f("ix_comment_post_slug"), table_name="comment")
  op.drop_table("comment")
  # ### end Alembic commands ###
