"""refresh models

Revision ID: 711b6679a35a
Revises: 1ba95a45cc2f
Create Date: 2026-10-08 11:00:16.709343

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "711b6679a35a"
down_revision: str | Sequence[str] | None = "1ba95a45cc2f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  pass
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  pass
  # ### end Alembic commands ###
