name: "Pull-Request"

on:
  pull_request:
    types: [synchronize, opened, reopened]

permissions:
  contents: read

jobs:
  secrets:
    name: secrets/scan
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        fetch-depth: 0
    - name: trufflehog
      uses: trufflesecurity/trufflehog@27b0417c16317ca9a472a9a8092acce143b49c55
      with:
        extra_args: --results=verified,unknown

  changes:
    needs: secrets
    name: changes/detect
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      backend_dockerfile: ${{ steps.changes.outputs.backend_dockerfile }}
      backend_python: ${{ steps.changes.outputs.backend_python }}
      frontend: ${{ steps.changes.outputs.frontend }}
      frontend_dockerfile: ${{ steps.changes.outputs.frontend_dockerfile }}
      frontend_js: ${{ steps.changes.outputs.frontend_js }}
      actions: ${{ steps.changes.outputs.actions }}
    steps:
    - name: checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        fetch-depth: 0
    - name: changes
      uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706
      id: changes
      with:
        filters: .github/file_and_dir_filters.yml

  backend:
    needs: changes
    name: backend/scan
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      security-events: read
    steps:
    - name: checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        fetch-depth: 0
    - name: dockerfile/scan
      uses: bridgecrewio/checkov-action@7b972723c44fb3d256283fac96fae5d7c1894bb7
      if: ${{ needs.changes.outputs.backend_dockerfile == 'true' }}
      with:
        output_format: cli
        output_file_path: console
        file: './backend/Dockerfile'
        framework: "dockerfile"
        quiet: true
    - name: codeql/init
      uses: github/codeql-action/init@7188fc363630916deb702c7fdcf4e481b751f97a
      if: ${{ needs.changes.outputs.backend_python == 'true' }}
      with:
        languages: python
        tools: linked
        build-mode: none
        config-file: ./.github/codeql/python-config.yml
    - name: codeql/analyze
      uses: github/codeql-action/analyze@7188fc363630916deb702c7fdcf4e481b751f97a
      if: ${{ needs.changes.outputs.backend_python == 'true' }}
      with:
        category: "/language:python"
    - name: docker/setup
      uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c
    - name: docker/build
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
      with:
        context: './backend/'
        push: false
        tags: local/web:back
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker
    - name: image/scan
      id: backend_scan
      uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2
      with:
        image: 'local/web:back'
        fail-build: true
        output-format: table
        severity-cutoff: high
        only-fixed: true
        config: .github/grype.yaml

  frontend:
    needs: changes
    name: frontend/scan
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      security-events: read
    steps:
    - name: checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        fetch-depth: 0
    - name: dockerfile/scan
      uses: bridgecrewio/checkov-action@7b972723c44fb3d256283fac96fae5d7c1894bb7
      if: ${{ needs.changes.outputs.frontend_dockerfile == 'true' }}
      with:
        output_format: cli
        output_file_path: console
        file: './frontend/Dockerfile'
        framework: "dockerfile"
        quiet: true
    - name: codeql/init
      uses: github/codeql-action/init@7188fc363630916deb702c7fdcf4e481b751f97a
      if: ${{ needs.changes.outputs.frontend_js == 'true' }}
      with:
        tools: linked
        languages: javascript-typescript
        build-mode: none
        config-file: ./.github/codeql/javascript-typescript-config.yml
    - name: codeql/analyze
      uses: github/codeql-action/analyze@7188fc363630916deb702c7fdcf4e481b751f97a
      if: ${{ needs.changes.outputs.frontend_js == 'true' }}
      with:
        category: "/language:javascript-typescript"
    - name: docker/setup
      uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c
    - name: docker/build
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
      with:
        context: './frontend/'
        push: false
        tags: local/web:front
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker
    - name: image/scan
      id: frontend_scan
      uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2
      with:
        image: 'local/web:front'
        fail-build: true
        output-format: table
        severity-cutoff: high
        only-fixed: true
        config: .github/grype.yaml

  actions:
    needs: changes
    name: actions/scan
    if: ${{ needs.changes.outputs.actions == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      security-events: read
    steps:
    - name: checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        fetch-depth: 0
    - name: codeql/init
      uses: github/codeql-action/init@7188fc363630916deb702c7fdcf4e481b751f97a
      with:
        tools: linked
        languages: actions
        build-mode: none
        config-file: ./.github/codeql/actions-config.yml
    - name: codeql/analyze
      uses: github/codeql-action/analyze@7188fc363630916deb702c7fdcf4e481b751f97a
      with:
        category: "/language:actions"

  success:
    runs-on: ubuntu-slim
    needs: [backend, frontend, actions]
    if: always()
    steps:
      - run: |
          if [[ ("${{ needs.backend.result }}" != "success" && "${{ needs.backend.result }}" != "skipped") || \
                ("${{ needs.actions.result }}" != "success" && "${{ needs.actions.result }}" != "skipped") || \
                ("${{ needs.frontend.result }}" != "success" && "${{ needs.frontend.result }}" != "skipped") ]]; then
            echo "❌ Failed :( Please check frontend or backend !!"
            exit 1
          fi
          echo "✅ All good :)"
